name: marker
base: core22
adopt-info: marker
version: '2023.05.02'
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
      bind: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/webkit2gtk-4.1

slots:
  marker:
    interface: dbus
    bus: session
    name: com.github.fabiocolacio.marker

apps:
  marker:
    command: usr/bin/marker
    extensions: [gnome]
    plugs:
      - home
      - network
      - network-status
      - network-bind
      - unity7
    common-id: com.github.fabiocolacio.marker
    desktop: usr/share/applications/com.github.fabiocolacio.marker.desktop

parts:
  marker:
    source: https://github.com/fabiocolacio/Marker.git
    source-tag: '2023.05.02'
    plugin: meson
    parse-info: [ usr/share/metainfo/com.github.fabiocolacio.marker.appdata.xml ]
    meson-parameters:
      - --prefix=/snap/marker/current/usr
    build-snaps:
      - cmake
    build-packages:
      - libghc-pandoc-dev
      - libgtksourceview-3.0-dev
      - libgtkspell3-3-dev
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/marker.patch

    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/snap/marker/current/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done
    organize:
      snap/marker/current: .
  deps:
    after: [ marker ]
    plugin: nil
    stage-packages:
      - libgtkspell3-3-0
      - pandoc
      - libgtksourceview-3.0-1
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgtkspell3-3.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgtkspell3-3.so.0.2.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/enchant-2/enchant_aspell.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/enchant-2/enchant_hspell.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/enchant-2/enchant_hunspell.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/libenchant-2.so.2
      - usr/lib/$CRAFT_ARCH_TRIPLET/libenchant-2.so.2.3.2
      - usr/bin/pandoc
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgtksourceview-3.0.so.1
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgtksourceview-3.0.so.1.8.0
